### PR TITLE
Address all outstanding sonarqube docker issues

### PR DESCRIPTION
**Pull request by peternied**
### Description
Fixed the following issues:
- Replace this shell form with exec form.
- Replace this invocation of wget with the ADD instruction.

Added exclusions for these issues:
- Surround this variable with double quotes; otherwise, it can lead to unexpected behavior.
- Merge this RUN instruction with the consecutive ones.
- Split this RUN instruction line into multiple lines.
- Use a specific version tag for the image.

### Issues Resolved
- Fix Docker SonarQube issues https://opensearch.atlassian.net/browse/MIGRATIONS-2241

### Testing
Ran sonarqube locally by using the CI workflow, verified it reports no more issues.

### Check List
- [ ] New functionality includes testing
  - [ ] All tests pass, including unit test, integration test and doctest
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
Down to 51 issues with this change
> ✅ Build passed: Found 51 issues, which is within the baseline of 89.

**Comment by peternied** [comment]
@sumobrian Would you mind taking a look at this PR?

**Comment by AndreKurait** [comment]
> Down to 51 issues with this change
> 
> > ✅ Build passed: Found 51 issues, which is within the baseline of 89.

Can we update the 89 to 51 in this change too?

**Comment by peternied** [comment]
@AndreKurait I would rather not tweak that number since it isn't meaningful in itself.  I'd rather we just get to zero a quickly as possible since we aren't blocking merges on these violations.

**Review by AndreKurait — APPROVED** [review]

**Pull request merged**
