### PR TITLE
Add plugin to check for CVE issues in dependencies to gradle files

### PR DESCRIPTION
**Pull request by okhasawn**
### Description
This PR adds the ability to check for any security vulnerabilities in the dependencies.

To run the security check, run the following command:
`gradle dependencyCheckAnalyze`

### Testing
[X]

### Check List
- [ ] New functionality includes testing
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mikaylathompson** [comment]
This is cool! Do you have any more information on where it's pulling the results from? I'm curious whether it's the same source as Mend or something else.

**Comment by okhasawn** [comment]
> This is cool! Do you have any more information on where it's pulling the results from? I'm curious whether it's the same source as Mend or something else.

Thanks Mikayla! Mend has this [database](https://www.mend.io/vulnerability-database/) and the plugin I added uses this [CVE database](https://cve.mitre.org/). I'm not sure how similar they are though.

**Review by gregschohn — COMMENTED** [review]
Dumb question - can you confirm the license on this?

**Comment by okhasawn** [comment]
> Dumb question - can you confirm the license on this?

@gregschohn - Good question actually. BTW I mentioned a while ago that I found this used in one of the aws repos.
Here's the [official link for the plugin](http://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html). It says this at the bottom: `"Permission to modify and redistribute is granted under the terms of the Apache 2.0 license."`

**Review by gregschohn — APPROVED** [review]

**Pull request merged**
