### PR TITLE
Replayer retry failed poll()

### PR DESCRIPTION
**Pull request by lewijacn**
### Description
When deploying our solution from a clean slate, the Replayer will continually fail at startup if the specified topic in Kafka is not available, with error: `Exception in thread "main" org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [logging-traffic-topic]` . This is seemingly because the Replayer does not have permission to create a topic and the Capture Proxy will not create a topic until it actually receives some incoming requests which makes starting with our solution an unpleasant experience. This change will allow the Replayer to continue to retry these failures without shutting down and spinning up another Replayer container.

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gregschohn** [comment]
Can the orchestrator/deployment process do this instead?

**Comment by lewijacn** [comment]
> Can the orchestrator/deployment process do this instead?

Not easily right now, would be a decent amount of effort to get things linked up so this is possible. I do think there's merit though in eventually having the orchestrator be able to clear a Kafka topic or determine the number of messages on a topic, things of this sort, and maybe creating the topics also fits into this pattern

**Comment by lewijacn** [comment]
@gregschohn Updated Replayer Kafka to continue to retry poll() exceptions

**Review by gregschohn — APPROVED** [review]
LGTM

**Pull request merged**
