### PR TITLE
Migrations-1126 - Add documentation on compatibility and running one-click deployment locally

### PR DESCRIPTION
**Pull request by okhasawn**
### Description
This PR adds a readme file to the TrafficCapture directory documenting how to run the solution and the compatibility of all the tools in that directory.

### Issues Resolved
[Migrations-1126](https://opensearch.atlassian.net/browse/MIGRATIONS-1126

### Check List
- [ ] New functionality includes testing
  - [ ] All tests pass, including unit test, integration test and doctest
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gregschohn — APPROVED** [review]
I agree w/ bjpres's comments about adding some more context.  It would be good to understand what "the Docker Solution" is.  Presume that the reader got kicked to the README from somewhere else and has no idea what this is.  Having even just a 2 sentence overview that says something like "The projects within this TrafficCapture directory facilitate proxying and capturing HTTP traffic en-route and offloading that traffic so that it can be replayed to other HTTP server(s)...".  You can then briefly describe which projects have top-level programs and then describe how the dockerSolution binds them all together into a single sandbox.
It's probably also a good idea to point to the architecture docs, which are currently up one level, but should probably move into this directory so that it is rooted under this readme rather than laterally.

**Review by sumobrian — APPROVED** [review]

**Comment by okhasawn** [comment]
> For this PR, can you reference this readme from the top level readme. A new user needs help understanding where to begin.
> 
> For a future change we should make a high quality top quality readme file. Here are some of the sections I recommend:
> 
>     * Getting Started
>       
>       * Why
>       * Directory Structure
>       * How things Work
> 
>     * Prerequisites
> 
>     * Installation
> 
>     * Usage
> 
>     * Contributing

Thank you @sumobrian, I think these would be great enhancments!



> I agree w/ bjpres's comments about adding some more context. It would be good to understand what "the Docker Solution" is. Presume that the reader got kicked to the README from somewhere else and has no idea what this is. Having even just a 2 sentence overview that says something like "The projects within this TrafficCapture directory facilitate proxying and capturing HTTP traffic en-route and offloading that traffic so that it can be replayed to other HTTP server(s)...". You can then briefly describe which projects have top-level programs and then describe how the dockerSolution binds them all together into a single sandbox. It's probably also a good idea to point to the architecture docs, which are currently up one level, but should probably move into this directory so that it is rooted under this readme rather than laterally.

Thank you @gregschohn, great idea! I just updated the readme file implementing a part of what you suggested while noting the other things which I do think will be very useful for the user!

**Comment by sumobrian** [comment]
@okhasawn  - Can you point me to the Jira ticket for these future enhancements?

**Comment by okhasawn** [comment]
> @okhasawn - Can you point me to the Jira ticket for these future enhancements?

@sumobrian - Sure thing! I just created it. [Migrations-1147](https://opensearch.atlassian.net/browse/MIGRATIONS-1147)

**Pull request merged**
