### PR TITLE
Onboard maven publish to 1-click release process

### PR DESCRIPTION
**Pull request by rishabh6788**
### Description
Add `publishToMaven` method to 1-click release job. 
I have set the auto-publishing to false to fist test if everything looks correct. 
Once verified will set it to `true`. 

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/4592

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rishabh6788** [comment]
cc: @gaiksaya Please take a look.

**Comment by AndreKurait** [comment]
@rishabh6788, Our gradle project is within a sub directory TrafficCapture that I think needs to be specified. See https://github.com/AndreKurait/opensearch-migrations/commit/ebf6b5cc6fb29aefb08d611b8a6e3d88ecab9650

**Review by gaiksaya — DISMISSED** [review]
Needs changes on github release drafter as well with right gradle command to bundle the artifact.

Do we still need to publish to artifacts.opensearch.org? Looks like the artifact was never released https://build.ci.opensearch.org/view/Release/job/opensearch-migrations-release/

If yes, in that case we need a mechanism to distinguish what needs to be published on maven and what needs to be published on S3

**Comment by AndreKurait** [comment]
Yes, we want to start publishing to artifacts as well. Let me know what change needs to be made to the gradle or github if i can help

**Comment by rishabh6788** [comment]
> Needs changes on github release drafter as well with right gradle command to bundle the artifact.
> 
> Do we still need to publish to artifacts.opensearch.org? Looks like the artifact was never released https://build.ci.opensearch.org/view/Release/job/opensearch-migrations-release/
> 
> If yes, in that case we need a mechanism to distinguish what needs to be published on maven and what needs to be published on S3

@gaiksaya As discussed I have moved the standard release pipeline logic into opensearch-migrations repo jenkinsfile. I have also updated the release-drafter workflow to generate maven jars and upload it to draft release. 

Please review the PR carefully and provide feedback.

**Review by AndreKurait — APPROVED** [review]

**Pull request merged**
