### PR TITLE
Include services.yaml hash in migration console 

### PR DESCRIPTION
**Pull request by AndreKurait**
### Description
Currently, some changes to the cdk.context.json will result in only the yaml getting updated in SSM and not trigger a re-deployment of the migration console which will result in stale parameters being used. This change alleviates this by updating generating a hash to put in the task definition so that a new task definition is created every time an update to the yaml is made.

* Category : Bug Fix
* Why these changes are required? Get rid of stale serivices.yaml
* What is the old behavior before changes and new behavior after changes? Sometimes, console would not be updated and remain with old values, now is fixed.

### Issues Resolved
[MIGRATIONS-1888](https://opensearch.atlassian.net/browse/MIGRATIONS-1888)

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
Deployed to AWS and verified successful startup and env variables include hash
image

### Check List
- [x] New functionality includes testing
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — CHANGES_REQUESTED** [review]
Thanks for integrating this, lets add test case to confirm that after the configuration is updated the migration console is redeployed.  I think this can be done by checking this by comparing the logical id of the container from `Template.fromStack(...)`.

**Comment by AndreKurait** [comment]
> Thanks for integrating this, lets add test case to confirm that after the configuration is updated the migration console is redeployed. I think this can be done by checking this by comparing the logical id of the container from `Template.fromStack(...)`.

Added this @peternied

**Comment by peternied** [comment]
@AndreKurait Looks like the CDK tests are failing?

**Review by mikaylathompson — APPROVED** [review]
Good solution for this, thanks!

**Comment by mikaylathompson** [comment]
You might need something like this: https://github.com/opensearch-project/opensearch-migrations/blob/main/deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts#L10-L11

**Pull request merged**
